
import { useState, useEffect } from 'react';
import { Download, Play, AlertCircle, CheckCircle, Info, ChevronDown } from 'lucide-react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import Sidebar from './reusable/Sidebar';

export default function BodyLanguageAnalysisFeedbackReport() {
  const [analysisData, setAnalysisData] = useState(null);
  const [duration, setDuration] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloadDropdown, setDownloadDropdown] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  // Get analysis result and duration from navigation state
  useEffect(() => {
    if (location.state?.analysisResult) {
      setAnalysisData(location.state.analysisResult);
      setDuration(location.state.duration || null);
      setLoading(false);
    } else {
      console.error('No analysis data received');
      setLoading(false);
    }
  }, [location.state]);

  // Function to get score color based on value (0-10 scale)
  const getScoreColor = (score) => {
    if (score === null || score === undefined) return 'bg-gray-300';
    if (score >= 8) return 'bg-gradient-to-r from-green-500 to-emerald-500';
    if (score >= 6) return 'bg-gradient-to-r from-yellow-500 to-amber-500';
    if (score >= 4) return 'bg-gradient-to-r from-orange-500 to-red-500';
    return 'bg-gradient-to-r from-red-500 to-rose-500';
  };

  // Function to get border color based on score
  const getBorderColor = (score) => {
    if (score === null || score === undefined) return 'border-gray-300';
    if (score >= 8) return 'border-green-200';
    if (score >= 6) return 'border-yellow-200';
    if (score >= 4) return 'border-orange-200';
    return 'border-red-200';
  };

  // Function to get score label
  const getScoreLabel = (score) => {
    if (score === null || score === undefined) return 'Not Analyzed';
    if (score >= 8) return 'Excellent';
    if (score >= 6) return 'Good';
    if (score >= 4) return 'Fair';
    return 'Needs Work';
  };

  // Format duration from seconds to minutes:seconds
  const formatDuration = (seconds) => {
    if (!seconds) return "Unknown";
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}m ${secs}s`;
  };

  // Function to handle report download in TXT format
  const handleDownloadTxt = () => {
    if (!analysisData) return;

    const reportContent = generateReportContent();
    const blob = new Blob([reportContent], { type: 'text/plain' });
    downloadFile(blob, 'body_language_analysis_report.txt');
    setDownloadDropdown(false);
  };

  // Function to handle report download in PDF format
  const handleDownloadPdf = async () => {
    if (!analysisData) return;

    try {
      const reportContent = generateReportContent();
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <html>
          <head>
            <title>Body Language Analysis Report</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
              h1 { color: #5B67CA; border-bottom: 2px solid #5B67CA; padding-bottom: 10px; }
              h2 { color: #374151; margin-top: 25px; }
              .section { margin: 20px 0; }
              .score { background: #f8f9fa; padding: 10px; border-left: 4px solid #5B67CA; }
              ul { margin: 10px 0; }
              li { margin: 5px 0; }
              .footer { margin-top: 40px; font-size: 12px; color: #6B7280; text-align: center; }
            </style>
          </head>
          <body>
            <h1>EXPRESSLY - BODY LANGUAGE ANALYSIS FEEDBACK REPORT</h1>
            <div class="section">
              <p><strong>Recorded:</strong> ${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleDateString() : 'Unknown'} • ${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleTimeString() : 'Unknown'} • <strong>Duration:</strong> ${formatDuration(duration)}</p>
              <p><strong>Overall Score:</strong> ${analysisData.overall?.score ?? 'N/A'}/10</p>
              <p><strong>Analysis Status:</strong> ${analysisData.status?.toUpperCase() ?? 'UNKNOWN'}</p>
            </div>
            ${generateHTMLReportContent()}
            <div class="footer">
              Generated by Expressly on ${new Date().toLocaleDateString()}
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    } catch (error) {
      console.error('Error generating PDF:', error);
      handleDownloadTxt();
    }
    setDownloadDropdown(false);
  };

  // Function to handle report download in DOCX format
  const handleDownloadDocx = async () => {
  if (!analysisData) return;

  try {
    // Create document with proper structure
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: "EXPRESSLY - BODY LANGUAGE ANALYSIS FEEDBACK REPORT",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 }
          }),
          
          // Recorded information
          new Paragraph({
            children: [
              new TextRun({
                text: "Recorded: ",
                bold: true
              }),
              new TextRun({
                text: `${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleDateString() : 'Unknown'} • ${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleTimeString() : 'Unknown'} • Duration: ${formatDuration(duration)}`
              })
            ],
            spacing: { after: 200 }
          }),
          
          // Overall Score
          new Paragraph({
            children: [
              new TextRun({
                text: "Overall Score: ",
                bold: true
              }),
              new TextRun({
                text: `${analysisData.overall?.score ?? 'N/A'}/10`
              })
            ],
            spacing: { after: 200 }
          }),
          
          // Analysis Status
          new Paragraph({
            children: [
              new TextRun({
                text: "Analysis Status: ",
                bold: true
              }),
              new TextRun({
                text: `${analysisData.status?.toUpperCase() ?? 'UNKNOWN'}`
              })
            ],
            spacing: { after: 400 }
          }),
          
          // Detailed Metrics Heading
          new Paragraph({
            text: "DETAILED METRICS",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 200 }
          }),
          
          // Metrics
          new Paragraph({
            children: [
              new TextRun({
                text: analysisData.posture?.score !== null ? 
                  `• Posture: ${analysisData.posture.score}/10 - ${getScoreLabel(analysisData.posture.score)}` : 
                  '• Posture: Not analyzed'
              })
            ],
            spacing: { after: 100 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: analysisData.gestures?.score !== null ? 
                  `• Gestures: ${analysisData.gestures.score}/10 - ${getScoreLabel(analysisData.gestures.score)}` : 
                  '• Gestures: Not analyzed'
              })
            ],
            spacing: { after: 100 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: analysisData.expressions?.score !== null ? 
                  `• Expressions: ${analysisData.expressions.score}/10 - ${getScoreLabel(analysisData.expressions.score)}` : 
                  '• Expressions: Not analyzed'
              })
            ],
            spacing: { after: 400 }
          }),
          
          // Performance Summary Heading
          new Paragraph({
            text: "PERFORMANCE SUMMARY",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 200 }
          }),
          
          // Strengths
          new Paragraph({
            children: [
              new TextRun({
                text: "Strengths:",
                bold: true
              })
            ],
            spacing: { after: 100 }
          }),
          ...(overallFeedback.Strengths && overallFeedback.Strengths.length > 0 ? 
            overallFeedback.Strengths.map(strength => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${strength}`
                  })
                ],
                spacing: { after: 100 }
              })
            ) : [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "• No notable strengths identified"
                  })
                ],
                spacing: { after: 100 }
              })
            ]
          ),
          
          // Areas for Improvement
          new Paragraph({
            children: [
              new TextRun({
                text: "Areas for Improvement:",
                bold: true
              })
            ],
            spacing: { before: 200, after: 100 }
          }),
          ...(overallFeedback.Weaknesses && overallFeedback.Weaknesses.length > 0 ? 
            overallFeedback.Weaknesses.map(weakness => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${weakness}`
                  })
                ],
                spacing: { after: 100 }
              })
            ) : [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "• No notable weaknesses identified"
                  })
                ],
                spacing: { after: 100 }
              })
            ]
          ),
          
          // Recommendations
          new Paragraph({
            children: [
              new TextRun({
                text: "Recommendations:",
                bold: true
              })
            ],
            spacing: { before: 200, after: 100 }
          }),
          ...(overallFeedback.SummaryOfTips && overallFeedback.SummaryOfTips.length > 0 ? 
            overallFeedback.SummaryOfTips.map(tip => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${tip}`
                  })
                ],
                spacing: { after: 100 }
              })
            ) : [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "• Keep practicing consistently"
                  })
                ],
                spacing: { after: 100 }
              })
            ]
          ),
          
          // Detailed Feedback Heading
          new Paragraph({
            text: "DETAILED FEEDBACK",
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 }
          }),
          
          // Posture Feedback
          ...(analysisData.posture?.feedback?.length > 0 ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: "Posture Analysis:",
                  bold: true
                })
              ],
              spacing: { after: 100 }
            }),
            ...analysisData.posture.feedback.map(feedback =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${feedback}`
                  })
                ],
                spacing: { after: 100 }
              })
            )
          ] : []),
          
          // Gestures Feedback
          ...(analysisData.gestures?.feedback?.length > 0 ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: "Gestures Analysis:",
                  bold: true
                })
              ],
              spacing: { before: 200, after: 100 }
            }),
            ...analysisData.gestures.feedback.map(feedback =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${feedback}`
                  })
                ],
                spacing: { after: 100 }
              })
            )
          ] : []),
          
          // Expressions Feedback
          ...(analysisData.expressions?.feedback?.length > 0 ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: "Expressions Analysis:",
                  bold: true
                })
              ],
              spacing: { before: 200, after: 100 }
            }),
            ...analysisData.expressions.feedback.map(feedback =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${feedback}`
                  })
                ],
                spacing: { after: 100 }
              })
            )
          ] : []),
          
          // Footer
          new Paragraph({
            text: `Generated by Expressly on ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 }
          })
        ]
      }]
    });

    // Generate the DOCX file
    const blob = await Packer.toBlob(doc);
    downloadFile(blob, 'body_language_analysis_report.docx');
    
  } catch (error) {
    console.error('Error generating DOCX:', error);
    // Fallback to simple text method
    const reportContent = generateReportContent();
    const blob = new Blob([reportContent], { 
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' 
    });
    downloadFile(blob, 'body_language_analysis_report.docx');
  }
  setDownloadDropdown(false);
};

  // Helper function to generate report content
  const generateReportContent = () => {
    return `
EXPRESSLY - BODY LANGUAGE ANALYSIS FEEDBACK REPORT

Recorded: ${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleDateString() : 'Unknown'} • ${analysisData.createdAt ? new Date(analysisData.createdAt).toLocaleTimeString() : 'Unknown'} • Duration: ${formatDuration(duration)}
Overall Score: ${analysisData.overall?.score ?? 'N/A'}/10
Analysis Status: ${analysisData.status?.toUpperCase() ?? 'UNKNOWN'}

DETAILED METRICS:
${analysisData.posture?.score !== null ? `- Posture: ${analysisData.posture.score}/10 - ${getScoreLabel(analysisData.posture.score)}` : '- Posture: Not analyzed'}
${analysisData.gestures?.score !== null ? `- Gestures: ${analysisData.gestures.score}/10 - ${getScoreLabel(analysisData.gestures.score)}` : '- Gestures: Not analyzed'}
${analysisData.expressions?.score !== null ? `- Expressions: ${analysisData.expressions.score}/10 - ${getScoreLabel(analysisData.expressions.score)}` : '- Expressions: Not analyzed'}

PERFORMANCE SUMMARY:
Strengths:
${analysisData.overall?.feedback?.Strengths?.map(strength => `  • ${strength}`).join('\n') || '  • No notable strengths identified'}

Areas for Improvement:
${analysisData.overall?.feedback?.Weaknesses?.map(weakness => `  • ${weakness}`).join('\n') || '  • No notable weaknesses identified'}

Recommendations:
${analysisData.overall?.feedback?.SummaryOfTips?.map(tip => `  • ${tip}`).join('\n') || '  • Keep practicing consistently'}

DETAILED FEEDBACK:
${analysisData.posture?.feedback?.length ? `Posture Analysis:\n${analysisData.posture.feedback.map(fb => `  • ${fb}`).join('\n')}` : ''}
${analysisData.gestures?.feedback?.length ? `\nGestures Analysis:\n${analysisData.gestures.feedback.map(fb => `  • ${fb}`).join('\n')}` : ''}
${analysisData.expressions?.feedback?.length ? `\nExpressions Analysis:\n${analysisData.expressions.feedback.map(fb => `  • ${fb}`).join('\n')}` : ''}
    `.trim();
  };

  // Helper function to generate HTML content for PDF
  const generateHTMLReportContent = () => {
    return `
      <div class="section">
        <h2>DETAILED METRICS</h2>
        <ul>
          ${analysisData.posture?.score !== null ? `<li>Posture: ${analysisData.posture.score}/10 - ${getScoreLabel(analysisData.posture.score)}</li>` : '<li>Posture: Not analyzed</li>'}
          ${analysisData.gestures?.score !== null ? `<li>Gestures: ${analysisData.gestures.score}/10 - ${getScoreLabel(analysisData.gestures.score)}</li>` : '<li>Gestures: Not analyzed</li>'}
          ${analysisData.expressions?.score !== null ? `<li>Expressions: ${analysisData.expressions.score}/10 - ${getScoreLabel(analysisData.expressions.score)}</li>` : '<li>Expressions: Not analyzed</li>'}
        </ul>
      </div>

      <div class="section">
        <h2>PERFORMANCE SUMMARY</h2>
        <h3>Strengths:</h3>
        <ul>
          ${analysisData.overall?.feedback?.Strengths?.map(strength => `<li>${strength}</li>`).join('') || '<li>No notable strengths identified</li>'}
        </ul>

        <h3>Areas for Improvement:</h3>
        <ul>
          ${analysisData.overall?.feedback?.Weaknesses?.map(weakness => `<li>${weakness}</li>`).join('') || '<li>No notable weaknesses identified</li>'}
        </ul>

        <h3>Recommendations:</h3>
        <ul>
          ${analysisData.overall?.feedback?.SummaryOfTips?.map(tip => `<li>${tip}</li>`).join('') || '<li>Keep practicing consistently</li>'}
        </ul>
      </div>

      <div class="section">
        <h2>DETAILED FEEDBACK</h2>
        ${analysisData.posture?.feedback?.length ? `<h3>Posture Analysis:</h3><ul>${analysisData.posture.feedback.map(fb => `<li>${fb}</li>`).join('')}</ul>` : ''}
        ${analysisData.gestures?.feedback?.length ? `<h3>Gestures Analysis:</h3><ul>${analysisData.gestures.feedback.map(fb => `<li>${fb}</li>`).join('')}</ul>` : ''}
        ${analysisData.expressions?.feedback?.length ? `<h3>Expressions Analysis:</h3><ul>${analysisData.expressions.feedback.map(fb => `<li>${fb}</li>`).join('')}</ul>` : ''}
      </div>
    `;
  };

  // Helper function to download files
  const downloadFile = (blob, filename) => {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.style.display = 'none';
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  // Function to handle navigation to practice page
  const navigateToPractice = () => {
    navigate('/practiceExercises');
  };

  if (loading) {
    return (
      <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
        <Sidebar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-[#5B67CA] border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gray-600 font-medium">Loading your analysis report...</p>
          </div>
        </div>
      </div>
    );
  }

  if (!analysisData) {
    return (
      <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
        <Sidebar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center bg-white/80 backdrop-blur-sm rounded-2xl p-8 shadow-lg border border-white/20">
            <AlertCircle className="w-20 h-20 text-red-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-800 mb-3">No Analysis Data</h2>
            <p className="text-gray-600 mb-6">Unable to load analysis results. Please try again.</p>
            <button 
              onClick={() => navigate('/recordVideo')}
              className="bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] hover:from-[#4a56b9] hover:to-[#7c3aed] text-white font-semibold px-8 py-3 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl"
            >
              Record New Video
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Safe data extraction from your exact structure
  const overallScore = analysisData.overall?.score ?? 0;
  const status = analysisData.status ?? 'unknown';
  const createdAt = analysisData.createdAt ? new Date(analysisData.createdAt) : new Date();
  
  // Correct logic for checking which components have scores
  const hasPosture = analysisData.posture?.score !== null && analysisData.posture?.score !== undefined;
  const hasGestures = analysisData.gestures?.score !== null && analysisData.gestures?.score !== undefined;
  const hasExpressions = analysisData.expressions?.score !== null && analysisData.expressions?.score !== undefined;

  // Get the actual feedback data from overall
  const overallFeedback = analysisData.overall?.feedback || {};

  return (
    <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <Sidebar />
      
      {/* Main Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-6xl mx-auto py-8 px-4">
          {/* Header */}
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 mb-8 border border-white/20">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between">
              <div className="flex-1">
                <h1 className="text-3xl font-bold bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] bg-clip-text text-transparent mb-2">
                  Body Language Analysis Report
                </h1>
                <div className="flex flex-wrap items-center gap-4 text-gray-600">
                  <span className="flex items-center gap-1">
                    <span className="text-lg">📅</span>
                    {createdAt.toLocaleDateString()}
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="text-lg">⏰</span>
                    {createdAt.toLocaleTimeString()}
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="text-lg">⏱️</span>
                    {formatDuration(duration)}
                  </span>
                </div>
              </div>
              <div className={`mt-4 lg:mt-0 px-4 py-2 rounded-full text-sm font-semibold border ${
                status === 'full' 
                  ? 'bg-gradient-to-r from-green-100 to-emerald-100 text-green-800 border-green-200' 
                  : status === 'partial'
                  ? 'bg-gradient-to-r from-yellow-100 to-amber-100 text-yellow-800 border-yellow-200'
                  : 'bg-gray-100 text-gray-800 border-gray-200'
              }`}>
                {status === 'full' ? '✅ Complete Analysis' : status === 'partial' ? '⚠️ Partial Analysis' : '❓ Unknown Status'}
              </div>
            </div>
          </div>
          
          <main className="space-y-8">
            {/* Overall Score */}
            <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 border border-white/20">
              <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between">
                <div className="flex-1">
                  <h2 className="text-2xl font-bold text-gray-800 mb-3">Overall Performance</h2>
                  <p className="text-gray-600 mb-4">Comprehensive analysis of your body language presentation</p>
                  {status === 'partial' && (
                    <div className="inline-flex items-center bg-yellow-50 text-yellow-700 px-4 py-2 rounded-lg border border-yellow-200">
                      <AlertCircle size={18} className="mr-2 flex-shrink-0" />
                      <span className="text-sm font-medium">Partial analysis - some components couldn't be analyzed</span>
                    </div>
                  )}
                </div>
                <div className="flex flex-col items-center mt-6 lg:mt-0">
                  <div className="relative w-32 h-32">
                    <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="#E6E6E6"
                        strokeWidth="3"
                      />
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="url(#scoreGradient)"
                        strokeWidth="3"
                        strokeDasharray={`${overallScore * 10}, 100`}
                        strokeLinecap="round"
                      />
                      <defs>
                        <linearGradient id="scoreGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#5B67CA" />
                          <stop offset="100%" stopColor="#8B5CF6" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center flex-col">
                      <span className="text-3xl font-bold text-gray-800">{overallScore}/10</span>
                      <span className="text-sm text-gray-500 mt-1">Overall Score</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Score Categories & Skipped Modules */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {hasPosture && (
                <ScoreCard 
                  title="Posture" 
                  score={analysisData.posture.score} 
                  feedback={analysisData.posture.feedback?.[0]}
                  color={getScoreColor(analysisData.posture.score)}
                  borderColor={getBorderColor(analysisData.posture.score)}
                  status={getScoreLabel(analysisData.posture.score)}
                />
              )}
              {hasGestures && (
                <ScoreCard 
                  title="Gestures" 
                  score={analysisData.gestures.score} 
                  feedback={analysisData.gestures.feedback?.[0]}
                  color={getScoreColor(analysisData.gestures.score)}
                  borderColor={getBorderColor(analysisData.gestures.score)}
                  status={getScoreLabel(analysisData.gestures.score)}
                />
              )}
              {hasExpressions && (
                <ScoreCard 
                  title="Expressions" 
                  score={analysisData.expressions.score} 
                  feedback={analysisData.expressions.feedback?.[0]}
                  color={getScoreColor(analysisData.expressions.score)}
                  borderColor={getBorderColor(analysisData.expressions.score)}
                  status={getScoreLabel(analysisData.expressions.score)}
                />
              )}
              
              {/* Skipped Modules */}
              {!hasPosture && (
                <SkippedModuleCard 
                  title="Posture" 
                  reason="Limited upper body visibility or lighting issues prevented accurate posture analysis."
                />
              )}
              {!hasGestures && (
                <SkippedModuleCard 
                  title="Gestures" 
                  reason="Hand movements were not clearly visible or person was too far from camera."
                />
              )}
              {!hasExpressions && (
                <SkippedModuleCard 
                  title="Expressions" 
                  reason="Facial features were not clearly visible due to lighting, angle, or distance."
                />
              )}
            </div>

            {/* Performance Summary - Combined with Detailed Feedback */}
            <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 border border-white/20">
              <h2 className="text-2xl font-bold text-gray-800 mb-6">Performance Insights</h2>
              
              <div className="grid lg:grid-cols-2 gap-8">
                {/* Strengths & Areas for Improvement */}
                <div className="space-y-6">
                  <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl p-6 border border-green-200">
                    <h3 className="text-lg font-semibold text-green-800 flex items-center mb-4">
                      <CheckCircle className="w-5 h-5 mr-2" />
                      Key Strengths
                    </h3>
                    <ul className="text-green-700 space-y-2">
                      {overallFeedback.Strengths && overallFeedback.Strengths.length > 0 ? (
                        overallFeedback.Strengths.map((strength, index) => (
                          <li key={index} className="flex items-start">
                            <span className="text-green-500 mr-2">•</span>
                            <span className="text-base">{strength}</span>
                          </li>
                        ))
                      ) : (
                        <li className="text-green-600 italic text-base">No notable strengths identified</li>
                      )}
                    </ul>
                  </div>
                  
                  <div className="bg-gradient-to-br from-yellow-50 to-amber-50 rounded-xl p-6 border border-yellow-200">
                    <h3 className="text-lg font-semibold text-yellow-800 flex items-center mb-4">
                      <AlertCircle className="w-5 h-5 mr-2" />
                      Areas for Improvement
                    </h3>
                    <ul className="text-yellow-700 space-y-2">
                      {overallFeedback.Weaknesses && overallFeedback.Weaknesses.length > 0 ? (
                        overallFeedback.Weaknesses.map((weakness, index) => (
                          <li key={index} className="flex items-start">
                            <span className="text-yellow-500 mr-2">•</span>
                            <span className="text-base">{weakness}</span>
                          </li>
                        ))
                      ) : (
                        <li className="text-yellow-600 italic text-base">No notable weaknesses identified</li>
                      )}
                    </ul>
                  </div>
                </div>

                {/* Recommendations & Detailed Feedback */}
                <div className="space-y-6">
                  <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-6 border border-blue-200">
                    <h3 className="text-lg font-semibold text-blue-800 mb-4">Recommendations</h3>
                    <ul className="text-blue-700 space-y-2">
                      {overallFeedback.SummaryOfTips && overallFeedback.SummaryOfTips.length > 0 ? (
                        overallFeedback.SummaryOfTips.map((tip, index) => (
                          <li key={index} className="flex items-start">
                            <span className="text-blue-500 mr-2">•</span>
                            <span className="text-base">{tip}</span>
                          </li>
                        ))
                      ) : (
                        <li className="text-blue-600 italic text-base">Keep practicing consistently</li>
                      )}
                    </ul>
                  </div>

                  {/* Component-specific detailed feedback */}
                  <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-6 border border-purple-200">
                    <h3 className="text-lg font-semibold text-purple-800 mb-4">Detailed Observations</h3>
                    <div className="space-y-4">
                      {analysisData.posture?.feedback?.length > 0 && (
                        <div>
                          <h4 className="font-semibold text-purple-700 mb-2">Posture</h4>
                          <ul className="text-purple-600 space-y-1">
                            {analysisData.posture.feedback.map((feedback, index) => (
                              <li key={index} className="flex items-start">
                                <span className="text-purple-400 mr-2">•</span>
                                <span className="text-base">{feedback}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {analysisData.gestures?.feedback?.length > 0 && (
                        <div>
                          <h4 className="font-semibold text-purple-700 mb-2">Gestures</h4>
                          <ul className="text-purple-600 space-y-1">
                            {analysisData.gestures.feedback.map((feedback, index) => (
                              <li key={index} className="flex items-start">
                                <span className="text-purple-400 mr-2">•</span>
                                <span className="text-base">{feedback}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {analysisData.expressions?.feedback?.length > 0 && (
                        <div>
                          <h4 className="font-semibold text-purple-700 mb-2">Expressions</h4>
                          <ul className="text-purple-600 space-y-1">
                            {analysisData.expressions.feedback.map((feedback, index) => (
                              <li key={index} className="flex items-start">
                                <span className="text-purple-400 mr-2">•</span>
                                <span className="text-base">{feedback}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-4 justify-center md:justify-end pt-4">
              <div className="relative">
                <button 
                  onClick={() => setDownloadDropdown(!downloadDropdown)}
                  className="flex items-center gap-2 bg-white hover:bg-gray-50 text-gray-800 font-semibold py-3 px-6 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl border border-gray-200"
                >
                  <Download size={18} />
                  Download Report
                  <ChevronDown size={16} className={`transition-transform ${downloadDropdown ? 'rotate-180' : ''}`} />
                </button>
                
                {downloadDropdown && (
                  <div className="absolute top-full right-0 mt-2 w-48 bg-white rounded-xl shadow-lg border border-gray-200 py-2 z-10">
                    <button 
                      onClick={handleDownloadTxt}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📄 Download as TXT
                    </button>
                    <button 
                      onClick={handleDownloadPdf}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📊 Download as PDF
                    </button>
                    <button 
                      onClick={handleDownloadDocx}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📝 Download as DOCX
                    </button>
                  </div>
                )}
              </div>
              
              <button 
                onClick={navigateToPractice}
                className="flex items-center gap-2 bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] hover:from-[#4a56b9] hover:to-[#7c3aed] text-white font-semibold py-3 px-6 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl"
              >
                <Play size={18} />
                Start Practice Session
              </button>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

function ScoreCard({ title, score, feedback, color, borderColor, status }) {
  return (
    <div className={`bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg p-6 border ${borderColor} hover:shadow-xl transition-all duration-300 group`}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-xl font-bold text-gray-800 group-hover:text-[#5B67CA] transition-colors">{title}</h3>
        <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${
          status === 'Excellent' ? 'bg-green-100 text-green-800 border-green-200' :
          status === 'Good' ? 'bg-yellow-100 text-yellow-800 border-yellow-200' :
          status === 'Fair' ? 'bg-orange-100 text-orange-800 border-orange-200' :
          status === 'Not Analyzed' ? 'bg-gray-100 text-gray-800 border-gray-200' :
          'bg-red-100 text-red-800 border-red-200'
        }`}>
          {status}
        </span>
      </div>
      
      <div className="relative h-3 bg-gray-200 rounded-full mb-4 overflow-hidden">
        <div 
          className={`absolute top-0 left-0 h-full rounded-full transition-all duration-1000 ease-out ${color}`} 
          style={{ width: `${(score || 0) * 10}%` }}
        />
      </div>
      
      <div className="flex items-center justify-between mb-4">
        <span className="text-2xl font-bold text-gray-800">{score}/10</span>
        <div className="text-sm text-gray-500 font-medium">
          Performance Score
        </div>
      </div>
      
      {feedback && (
        <p className="text-base text-gray-600 border-t border-gray-200 pt-4 mt-4">
          {feedback}
        </p>
      )}
    </div>
  );
}

function SkippedModuleCard({ title, reason }) {
  return (
    <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl shadow-lg p-6 border border-yellow-300 hover:shadow-xl transition-all duration-300">
      <div className="flex items-start mb-4">
        <div className="bg-yellow-100 p-3 rounded-xl mr-4">
          <AlertCircle className="w-6 h-6 text-yellow-600" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-gray-700">{title}</h3>
          <div className="bg-yellow-50 text-yellow-700 px-3 py-1 rounded-full text-xs font-semibold inline-block mt-2 border border-yellow-200">
            Analysis Skipped
          </div>
        </div>
      </div>
      
      <div className="bg-white/60 rounded-xl p-4 border border-yellow-200/50">
        <h4 className="text-sm font-semibold text-yellow-800 mb-2 flex items-center">
          <Info className="w-4 h-4 mr-1" />
          Reason for Skipping:
        </h4>
        <p className="text-base text-yellow-700 leading-relaxed">
          {reason}
        </p>
      </div>
      
      <div className="mt-4 text-xs text-gray-500 flex items-center">
        <Info className="w-3 h-3 mr-1" />
        Tip: Ensure good lighting and clear visibility for complete analysis
      </div>
    </div>
  );
}