import { useState, useEffect } from 'react';
import { Download, Play, AlertCircle, CheckCircle, Info, ChevronDown } from 'lucide-react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import Sidebar from './reusable/Sidebar';

export default function SpeechAnalysisFeedbackReport() {
  const [feedbackData, setFeedbackData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloadDropdown, setDownloadDropdown] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  // Get analysis result from navigation state
  useEffect(() => {
    if (location.state?.feedback) {
      setFeedbackData(location.state.feedback);
      setLoading(false);
    } else {
      console.error('No feedback data received');
      setLoading(false);
    }
  }, [location.state]);

  // Use dynamic scoring from backend with fallback
  const scoring = feedbackData?.scoring || { 
    scores: { pronunciation: 0, fluency: 0, pitch: 0, tone: 0 }, 
    overallScore: 0 
  };
  const pitch = location.state?.pitch || { overall: { monotone_chunks: 0, total_chunks: 0 } };
  const summary = feedbackData?.summary || { 
    strengths: "No data available", 
    improvements: "No data available", 
    recommendations: "No data available" 
  };
  const recordingInfo = feedbackData?.recordingInfo || { 
    date: new Date().toLocaleDateString(), 
    time: new Date().toLocaleTimeString(), 
    duration: "N/A" 
  };

  // Function to get score color based on value (0-100 scale)
  const getScoreColor = (score) => {
    if (score === null || score === undefined) return 'bg-gray-300';
    if (score >= 80) return 'bg-gradient-to-r from-green-500 to-emerald-500';
    if (score >= 60) return 'bg-gradient-to-r from-yellow-500 to-amber-500';
    if (score >= 40) return 'bg-gradient-to-r from-orange-500 to-red-500';
    return 'bg-gradient-to-r from-red-500 to-rose-500';
  };

  // Function to get border color based on score
  const getBorderColor = (score) => {
    if (score === null || score === undefined) return 'border-gray-300';
    if (score >= 80) return 'border-green-200';
    if (score >= 60) return 'border-yellow-200';
    if (score >= 40) return 'border-orange-200';
    return 'border-red-200';
  };

  // Function to get score label
  const getScoreLabel = (score) => {
    if (score === null || score === undefined) return 'Not Analyzed';
    if (score >= 80) return 'Excellent';
    if (score >= 60) return 'Good';
    if (score >= 40) return 'Fair';
    return 'Needs Work';
  };

  // Format duration
  const formatDuration = (duration) => {
    if (!duration || duration === "N/A") return "Unknown";
    return duration;
  };

  // Function to handle report download in TXT format
  const handleDownloadTxt = () => {
    const reportContent = generateReportContent();
    const blob = new Blob([reportContent], { type: 'text/plain' });
    downloadFile(blob, 'speech_analysis_report.txt');
    setDownloadDropdown(false);
  };

  // Function to handle report download in PDF format
  const handleDownloadPdf = async () => {
    try {
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <html>
          <head>
            <title>Speech Analysis Report</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
              h1 { color: #5B67CA; border-bottom: 2px solid #5B67CA; padding-bottom: 10px; }
              h2 { color: #374151; margin-top: 25px; }
              .section { margin: 20px 0; }
              .score { background: #f8f9fa; padding: 10px; border-left: 4px solid #5B67CA; }
              ul { margin: 10px 0; }
              li { margin: 5px 0; }
              .footer { margin-top: 40px; font-size: 12px; color: #6B7280; text-align: center; }
            </style>
          </head>
          <body>
            <h1>EXPRESSLY - SPEECH ANALYSIS FEEDBACK REPORT</h1>
            <div class="section">
              <p><strong>Recorded:</strong> ${recordingInfo.date} • ${recordingInfo.time} • <strong>Duration:</strong> ${formatDuration(recordingInfo.duration)}</p>
              <p><strong>Overall Score:</strong> ${scoring.overallScore}/100</p>
            </div>
            ${generateHTMLReportContent()}
            <div class="footer">
              Generated by Expressly on ${new Date().toLocaleDateString()}
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    } catch (error) {
      console.error('Error generating PDF:', error);
      handleDownloadTxt();
    }
    setDownloadDropdown(false);
  };

  // Function to handle report download in DOCX format
  const handleDownloadDocx = async () => {
    try {
      const doc = new Document({
        sections: [{
          properties: {},
          children: [
            new Paragraph({
              text: "EXPRESSLY - SPEECH ANALYSIS FEEDBACK REPORT",
              heading: HeadingLevel.HEADING_1,
              alignment: AlignmentType.CENTER,
              spacing: { after: 400 }
            }),
            
            // Recorded information
            new Paragraph({
              children: [
                new TextRun({
                  text: "Recorded: ",
                  bold: true
                }),
                new TextRun({
                  text: `${recordingInfo.date} • ${recordingInfo.time} • Duration: ${formatDuration(recordingInfo.duration)}`
                })
              ],
              spacing: { after: 200 }
            }),
            
            // Overall Score
            new Paragraph({
              children: [
                new TextRun({
                  text: "Overall Score: ",
                  bold: true
                }),
                new TextRun({
                  text: `${scoring.overallScore}/100`
                })
              ],
              spacing: { after: 400 }
            }),
            
            // Detailed Metrics Heading
            new Paragraph({
              text: "DETAILED METRICS",
              heading: HeadingLevel.HEADING_2,
              spacing: { after: 200 }
            }),
            
            // Metrics
            new Paragraph({
              children: [
                new TextRun({
                  text: `• Pronunciation: ${scoring.scores.pronunciation}% - ${getScoreLabel(scoring.scores.pronunciation)}`
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• Tone Analysis: ${scoring.scores.tone}% - ${getScoreLabel(scoring.scores.tone)}`
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• Pitch Variation: ${scoring.scores.pitch}% - ${getScoreLabel(scoring.scores.pitch)}`
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• Speech Clarity: ${scoring.scores.fluency}% - ${getScoreLabel(scoring.scores.fluency)}`
                })
              ],
              spacing: { after: 400 }
            }),
            
            // Performance Summary Heading
            new Paragraph({
              text: "PERFORMANCE SUMMARY",
              heading: HeadingLevel.HEADING_2,
              spacing: { after: 200 }
            }),
            
            // Strengths
            new Paragraph({
              children: [
                new TextRun({
                  text: "Strengths:",
                  bold: true
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• ${summary.strengths}`
                })
              ],
              spacing: { after: 200 }
            }),
            
            // Areas for Improvement
            new Paragraph({
              children: [
                new TextRun({
                  text: "Areas for Improvement:",
                  bold: true
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• ${summary.improvements}`
                })
              ],
              spacing: { after: 200 }
            }),
            
            // Recommendations
            new Paragraph({
              children: [
                new TextRun({
                  text: "Recommendations:",
                  bold: true
                })
              ],
              spacing: { after: 100 }
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `• ${summary.recommendations}`
                })
              ],
              spacing: { after: 400 }
            }),
            
            // Footer
            new Paragraph({
              text: `Generated by Expressly on ${new Date().toLocaleDateString()}`,
              alignment: AlignmentType.CENTER,
              spacing: { before: 600 }
            })
          ]
        }]
      });

      const blob = await Packer.toBlob(doc);
      downloadFile(blob, 'speech_analysis_report.docx');
      
    } catch (error) {
      console.error('Error generating DOCX:', error);
      const reportContent = generateReportContent();
      const blob = new Blob([reportContent], { 
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' 
      });
      downloadFile(blob, 'speech_analysis_report.docx');
    }
    setDownloadDropdown(false);
  };

  // Helper function to generate report content
  const generateReportContent = () => {
    return `
EXPRESSLY - SPEECH ANALYSIS FEEDBACK REPORT

Recorded: ${recordingInfo.date} • ${recordingInfo.time} • Duration: ${formatDuration(recordingInfo.duration)}
Overall Score: ${scoring.overallScore}/100

DETAILED METRICS:
- Pronunciation: ${scoring.scores.pronunciation}% - ${getScoreLabel(scoring.scores.pronunciation)}
- Tone Analysis: ${scoring.scores.tone}% - ${getScoreLabel(scoring.scores.tone)}
- Pitch Variation: ${scoring.scores.pitch}% - ${getScoreLabel(scoring.scores.pitch)}
- Speech Clarity: ${scoring.scores.fluency}% - ${getScoreLabel(scoring.scores.fluency)}

PERFORMANCE SUMMARY:
Strengths: ${summary.strengths}

Improvement Areas: ${summary.improvements}

Recommendations: ${summary.recommendations}

PITCH ANALYSIS DETAILS:
- Monotone Segments: ${pitch.overall.monotone_chunks}/${pitch.overall.total_chunks}
- Pitch Variation Score: ${scoring.scores.pitch}%
    `.trim();
  };

  // Helper function to generate HTML content for PDF
  const generateHTMLReportContent = () => {
    return `
      <div class="section">
        <h2>DETAILED METRICS</h2>
        <ul>
          <li>Pronunciation: ${scoring.scores.pronunciation}% - ${getScoreLabel(scoring.scores.pronunciation)}</li>
          <li>Tone Analysis: ${scoring.scores.tone}% - ${getScoreLabel(scoring.scores.tone)}</li>
          <li>Pitch Variation: ${scoring.scores.pitch}% - ${getScoreLabel(scoring.scores.pitch)}</li>
          <li>Speech Clarity: ${scoring.scores.fluency}% - ${getScoreLabel(scoring.scores.fluency)}</li>
        </ul>
      </div>

      <div class="section">
        <h2>PERFORMANCE SUMMARY</h2>
        <h3>Strengths:</h3>
        <p>${summary.strengths}</p>

        <h3>Areas for Improvement:</h3>
        <p>${summary.improvements}</p>

        <h3>Recommendations:</h3>
        <p>${summary.recommendations}</p>
      </div>

      <div class="section">
        <h2>PITCH ANALYSIS DETAILS</h2>
        <ul>
          <li>Monotone Segments: ${pitch.overall.monotone_chunks}/${pitch.overall.total_chunks}</li>
          <li>Pitch Variation Score: ${scoring.scores.pitch}%</li>
        </ul>
      </div>
    `;
  };

  // Helper function to download files
  const downloadFile = (blob, filename) => {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.style.display = 'none';
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  // Function to handle navigation to practice page
  const navigateToPractice = () => {
    navigate('/practiceSpeech');
  };

  if (loading) {
    return (
      <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
        <Sidebar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-[#5B67CA] border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gray-600 font-medium">Loading your analysis report...</p>
          </div>
        </div>
      </div>
    );
  }

  if (!feedbackData) {
    return (
      <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
        <Sidebar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center bg-white/80 backdrop-blur-sm rounded-2xl p-8 shadow-lg border border-white/20">
            <AlertCircle className="w-20 h-20 text-red-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-800 mb-3">No Analysis Data</h2>
            <p className="text-gray-600 mb-6">Unable to load analysis results. Please try again.</p>
            <button 
              onClick={() => navigate('/recordAudio')}
              className="bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] hover:from-[#4a56b9] hover:to-[#7c3aed] text-white font-semibold px-8 py-3 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl"
            >
              Record New Audio
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <Sidebar />
      
      {/* Main Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-6xl mx-auto py-8 px-4">
          {/* Header */}
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 mb-8 border border-white/20">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between">
              <div className="flex-1">
                <h1 className="text-3xl font-bold bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] bg-clip-text text-transparent mb-2">
                  Speech Analysis Feedback Report
                </h1>
                <div className="flex flex-wrap items-center gap-4 text-gray-600">
                  <span className="flex items-center gap-1">
                    <span className="text-lg">📅</span>
                    {recordingInfo.date}
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="text-lg">⏰</span>
                    {recordingInfo.time}
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="text-lg">⏱️</span>
                    {formatDuration(recordingInfo.duration)}
                  </span>
                </div>
              </div>
              <div className="mt-4 lg:mt-0 px-4 py-2 rounded-full text-sm font-semibold bg-gradient-to-r from-green-100 to-emerald-100 text-green-800 border border-green-200">
                ✅ Complete Analysis
              </div>
            </div>
          </div>
          
          <main className="space-y-8">
            {/* Overall Score */}
            <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 border border-white/20">
              <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between">
                <div className="flex-1">
                  <h2 className="text-2xl font-bold text-gray-800 mb-3">Overall Performance</h2>
                  <p className="text-gray-600 mb-4">Comprehensive analysis of your speech delivery and clarity</p>
                </div>
                <div className="flex flex-col items-center mt-6 lg:mt-0">
                  <div className="relative w-32 h-32">
                    <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="#E6E6E6"
                        strokeWidth="3"
                      />
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="url(#scoreGradient)"
                        strokeWidth="3"
                        strokeDasharray={`${scoring.overallScore}, 100`}
                        strokeLinecap="round"
                      />
                      <defs>
                        <linearGradient id="scoreGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#5B67CA" />
                          <stop offset="100%" stopColor="#8B5CF6" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center flex-col">
                      <span className="text-3xl font-bold text-gray-800">{scoring.overallScore}/100</span>
                      <span className="text-sm text-gray-500 mt-1">Overall Score</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Score Categories */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <ScoreCard 
                title="Pronunciation" 
                score={scoring.scores.pronunciation} 
                description="Accuracy and clarity of word pronunciation"
                color={getScoreColor(scoring.scores.pronunciation)}
                borderColor={getBorderColor(scoring.scores.pronunciation)}
                status={getScoreLabel(scoring.scores.pronunciation)}
              />
              <ScoreCard 
                title="Tone Analysis" 
                score={scoring.scores.tone} 
                description="Appropriate tone and emotional expression"
                color={getScoreColor(scoring.scores.tone)}
                borderColor={getBorderColor(scoring.scores.tone)}
                status={getScoreLabel(scoring.scores.tone)}
              />
              <ScoreCard 
                title="Pitch Variation" 
                score={scoring.scores.pitch} 
                description={`${pitch.overall.monotone_chunks}/${pitch.overall.total_chunks} monotone segments`}
                color={getScoreColor(scoring.scores.pitch)}
                borderColor={getBorderColor(scoring.scores.pitch)}
                status={getScoreLabel(scoring.scores.pitch)}
              />
              <ScoreCard 
                title="Speech Clarity" 
                score={scoring.scores.fluency} 
                description="Fluency and smoothness of speech delivery"
                color={getScoreColor(scoring.scores.fluency)}
                borderColor={getBorderColor(scoring.scores.fluency)}
                status={getScoreLabel(scoring.scores.fluency)}
              />
            </div>

            {/* Performance Summary */}
            <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl p-8 border border-white/20">
              <h2 className="text-2xl font-bold text-gray-800 mb-6">Performance Insights</h2>
              
              <div className="grid lg:grid-cols-2 gap-8">
                {/* Strengths & Areas for Improvement */}
                <div className="space-y-6">
                  <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl p-6 border border-green-200">
                    <h3 className="text-lg font-semibold text-green-800 flex items-center mb-4">
                      <CheckCircle className="w-5 h-5 mr-2" />
                      Key Strengths
                    </h3>
                    <div className="text-green-700">
                      <p className="text-base">{summary.strengths}</p>
                    </div>
                  </div>
                  
                  <div className="bg-gradient-to-br from-yellow-50 to-amber-50 rounded-xl p-6 border border-yellow-200">
                    <h3 className="text-lg font-semibold text-yellow-800 flex items-center mb-4">
                      <AlertCircle className="w-5 h-5 mr-2" />
                      Areas for Improvement
                    </h3>
                    <div className="text-yellow-700">
                      <p className="text-base">{summary.improvements}</p>
                    </div>
                  </div>
                </div>

                {/* Recommendations & Detailed Feedback */}
                <div className="space-y-6">
                  <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-6 border border-blue-200">
                    <h3 className="text-lg font-semibold text-blue-800 mb-4">Recommendations</h3>
                    <div className="text-blue-700">
                      <p className="text-base">{summary.recommendations}</p>
                    </div>
                  </div>

                  {/* Pitch Analysis Details */}
                  <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-6 border border-purple-200">
                    <h3 className="text-lg font-semibold text-purple-800 mb-4">Pitch Analysis Details</h3>
                    <div className="space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-purple-700">Monotone Segments:</span>
                        <span className="font-semibold text-purple-800">
                          {pitch.overall.monotone_chunks}/{pitch.overall.total_chunks}
                        </span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-purple-700">Pitch Variation Score:</span>
                        <span className="font-semibold text-purple-800">
                          {scoring.scores.pitch}%
                        </span>
                      </div>
                      <div className="mt-3 text-sm text-purple-600">
                        <Info className="w-4 h-4 inline mr-1" />
                        Lower monotone segments indicate better pitch variation
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-4 justify-center md:justify-end pt-4">
              <div className="relative">
                <button 
                  onClick={() => setDownloadDropdown(!downloadDropdown)}
                  className="flex items-center gap-2 bg-white hover:bg-gray-50 text-gray-800 font-semibold py-3 px-6 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl border border-gray-200"
                >
                  <Download size={18} />
                  Download Report
                  <ChevronDown size={16} className={`transition-transform ${downloadDropdown ? 'rotate-180' : ''}`} />
                </button>
                
                {downloadDropdown && (
                  <div className="absolute top-full right-0 mt-2 w-48 bg-white rounded-xl shadow-lg border border-gray-200 py-2 z-10">
                    <button 
                      onClick={handleDownloadTxt}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📄 Download as TXT
                    </button>
                    <button 
                      onClick={handleDownloadPdf}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📊 Download as PDF
                    </button>
                    <button 
                      onClick={handleDownloadDocx}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      📝 Download as DOCX
                    </button>
                  </div>
                )}
              </div>
              
              <button 
                onClick={navigateToPractice}
                className="flex items-center gap-2 bg-gradient-to-r from-[#5B67CA] to-[#8B5CF6] hover:from-[#4a56b9] hover:to-[#7c3aed] text-white font-semibold py-3 px-6 rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl"
              >
                <Play size={18} />
                Start Practice Session
              </button>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

// Enhanced Score Card Component with thinner colored borders
function ScoreCard({ title, score, description, color, borderColor, status }) {
  return (
    <div className={`bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg p-6 border ${borderColor} hover:shadow-xl transition-all duration-300 group`}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-xl font-bold text-gray-800 group-hover:text-[#5B67CA] transition-colors">{title}</h3>
        <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${
          status === 'Excellent' ? 'bg-green-100 text-green-800 border-green-200' :
          status === 'Good' ? 'bg-yellow-100 text-yellow-800 border-yellow-200' :
          status === 'Fair' ? 'bg-orange-100 text-orange-800 border-orange-200' :
          status === 'Not Analyzed' ? 'bg-gray-100 text-gray-800 border-gray-200' :
          'bg-red-100 text-red-800 border-red-200'
        }`}>
          {status}
        </span>
      </div>
      
      <div className="relative h-3 bg-gray-200 rounded-full mb-4 overflow-hidden">
        <div 
          className={`absolute top-0 left-0 h-full rounded-full transition-all duration-1000 ease-out ${color}`} 
          style={{ width: `${score || 0}%` }}
        />
      </div>
      
      <div className="flex items-center justify-between mb-4">
        <span className="text-2xl font-bold text-gray-800">{score}%</span>
        <div className="text-sm text-gray-500 font-medium">
          Performance Score
        </div>
      </div>
      
      {description && (
        <p className="text-base text-gray-600 border-t border-gray-200 pt-4 mt-4">
          {description}
        </p>
      )}
    </div>
  );
}